add_test( Pythagoras.Norm /workspaces/lab-01-GandhiYogesh/build-container/gtest [==[--gtest_filter=Pythagoras.Norm]==] --gtest_also_run_disabled_tests)
set_tests_properties( Pythagoras.Norm PROPERTIES WORKING_DIRECTORY /workspaces/lab-01-GandhiYogesh/build-container)
add_test( Pythagoras.Distance /workspaces/lab-01-GandhiYogesh/build-container/gtest [==[--gtest_filter=Pythagoras.Distance]==] --gtest_also_run_disabled_tests)
set_tests_properties( Pythagoras.Distance PROPERTIES WORKING_DIRECTORY /workspaces/lab-01-GandhiYogesh/build-container)
add_test( Pythagoras.ScalarProduct /workspaces/lab-01-GandhiYogesh/build-container/gtest [==[--gtest_filter=Pythagoras.ScalarProduct]==] --gtest_also_run_disabled_tests)
set_tests_properties( Pythagoras.ScalarProduct PROPERTIES WORKING_DIRECTORY /workspaces/lab-01-GandhiYogesh/build-container)
add_test( Pythagoras3.Norm3 /workspaces/lab-01-GandhiYogesh/build-container/gtest [==[--gtest_filter=Pythagoras3.Norm3]==] --gtest_also_run_disabled_tests)
set_tests_properties( Pythagoras3.Norm3 PROPERTIES WORKING_DIRECTORY /workspaces/lab-01-GandhiYogesh/build-container)
add_test( Pythagoras3.Distance3 /workspaces/lab-01-GandhiYogesh/build-container/gtest [==[--gtest_filter=Pythagoras3.Distance3]==] --gtest_also_run_disabled_tests)
set_tests_properties( Pythagoras3.Distance3 PROPERTIES WORKING_DIRECTORY /workspaces/lab-01-GandhiYogesh/build-container)
add_test( Pythagoras3.ScalarProduct3 /workspaces/lab-01-GandhiYogesh/build-container/gtest [==[--gtest_filter=Pythagoras3.ScalarProduct3]==] --gtest_also_run_disabled_tests)
set_tests_properties( Pythagoras3.ScalarProduct3 PROPERTIES WORKING_DIRECTORY /workspaces/lab-01-GandhiYogesh/build-container)
set( gtest_TESTS Pythagoras.Norm Pythagoras.Distance Pythagoras.ScalarProduct Pythagoras3.Norm3 Pythagoras3.Distance3 Pythagoras3.ScalarProduct3)
